using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DungeonFinal
{
    class GreaterManaRegeneration : StatusEffect
    {
        public GreaterManaRegeneration()
        {
            setDuration(5);
        }

        public override String Modify()
        {
            getHero().setCurMana(getHero().getCurMana() + 20);             
            setDuration(getDuration() - 1);

            if (getDuration() > 0)
            {
                return (getHero().getName() + " mana is being regenerated by 20 for " + getDuration() + " more turn(s)!\r\n");
            }

            else
            {
                return (getHero().getName() + " mana regeneration potion has ended!\r\n");
            }
        }
    }
}
