using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace DungeonFinal
{
    class GreaterHealthRegeneration : StatusEffect
    {
        public GreaterHealthRegeneration()
        {
            setDuration(5);
        }

        public override String Modify()
        {
            getHero().setCurHealth(getHero().getCurHealth() + 20);             
            setDuration(getDuration() - 1);

            if (getDuration() > 0)
            {
                return (getHero().getName() + " health is being regenerated by 20 for " + getDuration() + " more turn(s)!\r\n");
            }

            else
            {
                return (getHero().getName() + " greater health regeneration potion has ended!\r\n");
            }
        }
    }
}
